### ISSUE TITLE
Client crash when monitor block is placed on server

### ISSUE THREAD

**Issue by SuperSpaceEye** [tom5454/Toms-Peripherals#1]
On server if monitor block is placed, server shows this error (but doesn't crash)
```
[15:47:55] [Netty Server IO #4/ERROR] [minecraft/PacketEncoder]: Error receiving packet 34
java.lang.NullPointerException: Cannot read the array length because "this.f_128600_" is null
	at net.minecraft.nbt.IntArrayTag.m_6434_(IntArrayTag.java:82) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.nbt.CompoundTag.m_128368_(CompoundTag.java:446) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.nbt.CompoundTag.m_6434_(CompoundTag.java:134) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.nbt.NbtIo.m_128950_(NbtIo.java:265) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.nbt.NbtIo.m_128941_(NbtIo.java:234) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_130079_(FriendlyByteBuf.java:405) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195693_(ClientboundLevelChunkPacketData.java:149) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.m_195671_(ClientboundLevelChunkPacketData.java:70) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.network.FriendlyByteBuf.m_178352_(FriendlyByteBuf.java:129) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.m_195666_(ClientboundLevelChunkPacketData.java:70) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.m_5779_(ClientboundLevelChunkWithLightPacket.java:39) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:45) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at net.minecraft.network.Connection.m_178303_(Connection.java:214) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:203) ~[server-1.18.2-20220404.173914-srg.jar%2358!/:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar%2330!/:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[15:47:55] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: SpaceEye2 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot read the array length because "this.f_128600_" is null

```

**Comment by SuperSpaceEye** [comment]
and client shows this error 
```
[04Nov2023 15:47:56.612] [Render thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at net.minecraftforge.network.filters.NetworkFilters.lambda$injectIfNecessary$1(NetworkFilters.java:34) ~[forge-1.18.2-40.2.9-universal.jar%2384!/:?]
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:196) ~[guava-31.0.1-jre.jar%2330!/:?]
	at net.minecraftforge.network.filters.NetworkFilters.injectIfNecessary(NetworkFilters.java:30) ~[forge-1.18.2-40.2.9-universal.jar%2384!/:?]
	at net.minecraftforge.network.NetworkHooks.sendMCRegistryPackets(NetworkHooks.java:108) ~[forge-1.18.2-40.2.9-universal.jar%2384!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5998_(ClientPacketListener.java:375) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?]
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:83) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?]
	at net.minecraft.network.protocol.game.ClientboundLoginPacket.m_5797_(ClientboundLoginPacket.java:19) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2379!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.9.jar%2318!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

**Comment by SuperSpaceEye** [comment]
Version 1.18.2, mods 
![image](https://github.com/tom5454/Toms-Peripherals/assets/44544509/df40ed52-6dc9-4829-b99d-463ab2c28430)

**Comment by SuperSpaceEye** [comment]
both on forge and fabrix
